export const makes = [
  {
    'code': 'PACK',
    'description': 'PACKARD',
    'type': 'V',
  }, {
    'code': 'PANO',
    'description': 'PANOZ',
    'type': 'V',
  }, {
    'code': 'PANT',
    'description': 'PANTERA',
    'type': 'V',
  }, {
    'code': 'PEUG',
    'description': 'PEUGEOT',
    'type': 'V',
  }, {
    'code': 'PHIL',
    'description': 'PHILLIPS',
    'type': 'V',
  }, {
    'code': 'PHOE',
    'description': 'PHOENIX',
    'type': 'V',
  }, {
    'code': 'PIRC',
    'description': 'PIERCE',
    'type': 'V',
  }, {
    'code': 'PLYM',
    'description': 'PLYMOUTH',
    'type': 'V',
  }, {
    'code': 'PONT',
    'description': 'PONTIAC',
    'type': 'V',
  }, {
    'code': 'PORS',
    'description': 'PORSCHE',
    'type': 'V',
  }, {
    'code': 'PUMA',
    'description': 'PUMA',
    'type': 'V',
  }, {
    'code': 'RALT',
    'description': 'RALT',
    'type': 'V',
  }, {
    'code': 'RAM',
    'description': 'RAM TRUCKS',
    'type': 'V',
  }, {
    'code': 'RANG',
    'description': 'RANGE ROVER',
    'type': 'V',
  }, {
    'code': 'RAUC',
    'description': 'RAUCH',
    'type': 'V',
  }, {
    'code': 'RENA',
    'description': 'RENAULT',
    'type': 'V',
  }, {
    'code': 'RMR',
    'description': 'ROADMASTER RAIL',
    'type': 'V',
  }, {
    'code': 'ROL',
    'description': 'ROLLS ROYCE',
    'type': 'V',
  }, {
    'code': 'ROVE',
    'description': 'ROVER',
    'type': 'V',
  }, {
    'code': 'RUF',
    'description': 'RUF',
    'type': 'V',
  }, {
    'code': 'SAA',
    'description': 'SAAB',
    'type': 'V',
  }, {
    'code': 'SALE',
    'description': 'SALEEN',
    'type': 'V',
  }, {
    'code': 'SATU',
    'description': 'SATURN',
    'type': 'V',
  }, {
    'code': 'SCIO',
    'description': 'SCION',
    'type': 'V',
  }, {
    'code': 'SHAY',
    'description': 'SHAY',
    'type': 'V',
  }, {
    'code': 'SHEL',
    'description': 'SHELBY',
    'type': 'V',
  }, {
    'code': 'SMRT',
    'description': 'SMART CARS',
    'type': 'V',
  }, {
    'code': 'STLG',
    'description': 'STERLING',
    'type': 'V',
  }, {
    'code': 'STUD',
    'description': 'STUDEBAKER',
    'type': 'V',
  }, {
    'code': 'SUBA',
    'description': 'SUBARU',
    'type': 'V',
  }, {
    'code': 'SUNB',
    'description': 'SUNBEAM',
    'type': 'V',
  }, {
    'code': 'SUZI',
    'description': 'SUZUKI',
    'type': 'V',
  }, {
    'code': 'TESL',
    'description': 'TESLA',
    'type': 'V',
  }, {
    'code': 'TOP',
    'description': 'TOP HAT',
    'type': 'V',
  }, {
    'code': 'TOYT',
    'description': 'TOYOTA',
    'type': 'V',
  }, {
    'code': 'TRAB',
    'description': 'TRABANT',
    'type': 'V',
  }, {
    'code': 'TRIU',
    'description': 'TRIUMPH',
    'type': 'V',
  }, {
    'code': 'TVR',
    'description': 'TVR',
    'type': 'V',
  }, {
    'code': 'UTIM',
    'description': 'UTILIMASTER',
    'type': 'V',
  }, {
    'code': 'UTIL',
    'description': 'UTILITY',
    'type': 'V',
  }, {
    'code': 'VAZ',
    'description': 'VAZ',
    'type': 'V',
  }, {
    'code': 'VESP',
    'description': 'VESPA',
    'type': 'V',
  }, {
    'code': 'VEXE',
    'description': 'VEXEL',
    'type': 'V',
  }, {
    'code': 'VOLG',
    'description': 'VOLGA',
    'type': 'V',
  }, {
    'code': 'VOLK',
    'description': 'VOLKSWAGEN',
    'type': 'V',
  }, {
    'code': 'VOLV',
    'description': 'VOLVO',
    'type': 'V',
  }, {
    'code': 'VPG',
    'description': 'VPG',
    'type': 'V',
  }, {
    'code': 'VPLA',
    'description': 'VPLAUS',
    'type': 'V',
  }, {
    'code': 'WHEE',
    'description': 'WHEEGO',
    'type': 'V',
  }, {
    'code': 'WILL',
    'description': 'WILLY',
    'type': 'V',
  }, {
    'code': 'YAMA',
    'description': 'YAMAHA',
    'type': 'V',
  },
] // eslint-disable-line
